ARG from
FROM $from

COPY etc/ /etc/

COPY var/ /var/

# kernel
RUN mkdir -p /boot/dtb && \
    dnf -y remove \
        kernel \
        kernel-core \
        kernel-modules \
        kernel-modules-core && \
    dnf -y copr enable kireevm96/sm8250 && \
    dnf -y install --from-repo='copr:copr.fedorainfracloud.org:kireevm96:sm8250' 'kernel-0:6.15.11-1.pipa.*' 'kernel-headers-0:6.15.11-1.pipa.*' && \
    rm -r /boot/dtb

RUN dnf -y install \
    xiaomi-pipa-firmware \
    qbootctl \
    pipa-dracut \
    pipa-sound-conf \
    bootmac

RUN kver=$(rpm -q --qf '%{VERSION}-%{RELEASE}' kernel) && \
    dracut -vf --kver $kver /usr/lib/modules/$kver/initramfs.img

RUN systemctl enable qbootctl.service bootmac-bluetooth

# cleanup
RUN dnf clean all && rm -rf /var/log/*

RUN bootc container lint --no-truncate
