name: containers
on:
  workflow_dispatch:
    inputs:
      fedora_branch:
        type: choice
        description: 'fedora branch'
        required: true
        options:
          - '42'
          - '43'
          - 'rawhide'
        default: '42'
  push:
    paths:
      - 'base/**'
      - 'devices/*/container/**'
      - 'desktops/**'

run-name: "containers: fedora ${{ inputs.fedora_branch || 42 }} ${{ github.event_name == 'push' && format(' | {0}', github.event.head_commit.message) || '' }}"

jobs:
  base:
    secrets: inherit
    permissions:
      packages: write
    uses: ./.github/workflows/helper-build-container.yml
    with:
      from_tag: ${{ inputs.fedora_branch || 42 }}
      from_image: quay.io/fedora/fedora-bootc
      target_image: base
      context: base
      rechunk: false

  devices:
    needs: base
    permissions:
      packages: write
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        device: [xiaomi-nabu, xiaomi-pipa, oneplus-sdm845, nothing-spacewar, xunlong-orangepi3]
    uses: ./.github/workflows/helper-build-device.yml
    with:
      device: ${{ matrix.device }}
      from_tag: ${{ needs.base.outputs.target_tag }}
      registry: ${{ needs.base.outputs.registry }}
